### ISSUE TITLE
is still alive the project?

### ISSUE THREAD

**Issue by Allan-Nava** [jacksonofalltrades/pydeepstream#8]

**Comment by viridia** [comment]
nope

**Comment by Allan-Nava** [comment]
> nope

So i can't use in production? I need to integate with django

**Comment by viridia** [comment]
Best way to integrate with Django is to use the deepstream HTTP interface.

You can't use this library to integrate with Django because it requires websockets which are incompatible with WSGI (which is what Django is based on). Websockets require a continue ping / pong heartbeat to keep alive, and WSGI doesn't allow this because no code can run unless there's an active HTTP request being serviced.

This project is dead because the company that funded it is no longer using deepstream.
